#!/bin/sh
# Bootstrap Garage: layout, bucket "pdfs", key "app-key", and permissions.
# Run once after first `docker compose up garage`. Idempotent (safe to re-run).
#
# Usage: from repo root: ./infra/scripts/garage_bootstrap.sh
#    or: cd infra/docker && ../scripts/garage_bootstrap.sh

set -e

GARAGE_CONTAINER="${GARAGE_CONTAINER:-garage}"
BUCKET="${GARAGE_BUCKET:-pdfs}"
KEY_NAME="${GARAGE_KEY_NAME:-app-key}"
ZONE="${GARAGE_ZONE:-dc1}"
CAPACITY="${GARAGE_CAPACITY:-1G}"

garage_exec() {
  docker exec "$GARAGE_CONTAINER" /garage "$@"
}

echo "Waiting for Garage to be ready..."
for i in 1 2 3 4 5 6 7 8 9 10; do
  if garage_exec status 2>/dev/null | grep -qE '^[0-9a-f]{16}[[:space:]]'; then
    break
  fi
  [ "$i" -eq 10 ] && { echo "Garage did not become ready in time."; exit 1; }
  sleep 2
done

STATUS_OUT="$(garage_exec status 2>/dev/null)"
NODE_ID="$(echo "$STATUS_OUT" | awk '/^[0-9a-f]{16}[[:space:]]/ {print $1; exit}')"

if [ -z "$NODE_ID" ]; then
  echo "Could not parse node ID from garage status."
  exit 1
fi

# Layout: assign + apply if node has no role
if echo "$STATUS_OUT" | grep -q "NO ROLE ASSIGNED"; then
  echo "Assigning layout for node $NODE_ID..."
  garage_exec layout assign -z "$ZONE" -c "$CAPACITY" "$NODE_ID"
  garage_exec layout apply --version 1
  echo "Layout applied."
else
  echo "Layout already assigned, skipping."
fi

# Bucket
if garage_exec bucket list 2>/dev/null | grep -qw "$BUCKET"; then
  echo "Bucket '$BUCKET' already exists, skipping."
else
  garage_exec bucket create "$BUCKET"
  echo "Bucket '$BUCKET' created."
fi

# Key (secret shown only at creation; if exists we cannot retrieve it)
KEY_CREATED=0
SECRETS_DIR="${GARAGE_SECRETS_DIR:-/secrets}"
S3_CREDS_FILE="$SECRETS_DIR/garage_s3_creds"

if garage_exec key list 2>/dev/null | grep -qw "$KEY_NAME"; then
  echo "Key '$KEY_NAME' already exists, skipping creation."
else
  echo "Creating key '$KEY_NAME'..."
  KEY_OUT="$(garage_exec key create "$KEY_NAME" 2>/dev/null)"
  echo "$KEY_OUT"
  KEY_ID="$(echo "$KEY_OUT" | awk -F': ' '/Key ID:/ { print $2; exit }' | tr -d ' ')"
  SECRET_KEY="$(echo "$KEY_OUT" | awk -F': ' '/Secret key:/ { print $2; exit }' | tr -d ' ')"

  if [ -n "$KEY_ID" ] && [ -n "$SECRET_KEY" ] && [ -d "$SECRETS_DIR" ]; then
    {
      echo "# Garage S3 credentials - generated by garage_bootstrap.sh"
      echo "# Source this file or use with your S3 client."
      echo "AWS_ACCESS_KEY_ID=$KEY_ID"
      echo "AWS_SECRET_ACCESS_KEY=$SECRET_KEY"
      echo "AWS_ENDPOINT_URL=http://127.0.0.1:3900"
      echo "AWS_DEFAULT_REGION=garage"
      echo "S3_BUCKET=$BUCKET"
    } > "$S3_CREDS_FILE"
    chmod 600 "$S3_CREDS_FILE" 2>/dev/null || true
    echo "Credentials written to $S3_CREDS_FILE"
    echo "  (If owned by root: chown to your user, e.g. infra/docker/garage/secrets/garage_s3_creds)"
  else
    echo "WARNING: Could not write credentials to $S3_CREDS_FILE (save the secret above)"
  fi
  KEY_CREATED=1
fi

# Allow key on bucket
garage_exec bucket allow --read --write --owner "$BUCKET" --key "$KEY_NAME"
echo "Key '$KEY_NAME' has RWO on bucket '$BUCKET'."

if [ "$KEY_CREATED" -eq 0 ]; then
  if [ -f "$S3_CREDS_FILE" ]; then
    echo "Existing credentials in $S3_CREDS_FILE"
  else
    echo "Key already existed. Run 'docker exec $GARAGE_CONTAINER /garage key info $KEY_NAME' for Key ID (secret is redacted)."
  fi
fi
