#!/bin/sh
# Bootstrap Garage: layout, buckets, key "app-key", and permissions.
# Run once after first `docker compose up garage`. Idempotent (safe to re-run).
#
# Usage: from repo root: ./infra/scripts/garage_bootstrap.sh
#    or: cd infra/docker && ../scripts/garage_bootstrap.sh

set -e

GARAGE_CONTAINER="${GARAGE_CONTAINER:-garage}"
KEY_NAME="${GARAGE_KEY_NAME:-app-key}"
ZONE="${GARAGE_ZONE:-dc1}"
CAPACITY="${GARAGE_CAPACITY:-1G}"

garage_exec() {
  docker exec "$GARAGE_CONTAINER" /garage "$@"
}

echo "Waiting for Garage to be ready..."
for i in 1 2 3 4 5 6 7 8 9 10; do
  if garage_exec status 2>/dev/null | grep -qE '^[0-9a-f]{16}[[:space:]]'; then
    break
  fi
  [ "$i" -eq 10 ] && { echo "Garage did not become ready in time."; exit 1; }
  sleep 2
done

STATUS_OUT="$(garage_exec status 2>/dev/null)"
NODE_ID="$(echo "$STATUS_OUT" | awk '/^[0-9a-f]{16}[[:space:]]/ {print $1; exit}')"

if [ -z "$NODE_ID" ]; then
  echo "Could not parse node ID from garage status."
  exit 1
fi

# Layout: assign + apply if node has no role
if echo "$STATUS_OUT" | grep -q "NO ROLE ASSIGNED"; then
  echo "Assigning layout for node $NODE_ID..."
  garage_exec layout assign -z "$ZONE" -c "$CAPACITY" "$NODE_ID"
  garage_exec layout apply --version 1
  echo "Layout applied."
else
  echo "Layout already assigned, skipping."
fi

DEFAULT_BUCKETS_CSV="pdfs,docling,rendered,chunks,langfuse"
if [ -n "${GARAGE_BUCKETS+x}" ] && [ -n "${GARAGE_BUCKETS:-}" ]; then
  BUCKETS_CSV="$GARAGE_BUCKETS"
  echo "Using GARAGE_BUCKETS='$BUCKETS_CSV'"
elif [ -n "${GARAGE_BUCKET+x}" ] && [ -n "${GARAGE_BUCKET:-}" ]; then
  BUCKETS_CSV="$GARAGE_BUCKET"
  echo "Using GARAGE_BUCKET='$BUCKETS_CSV'"
else
  BUCKETS_CSV="$DEFAULT_BUCKETS_CSV"
  echo "Using default buckets '$BUCKETS_CSV'"
fi

BUCKETS="$(printf '%s' "$BUCKETS_CSV" | tr ',' ' ')"

# Buckets
PRIMARY_BUCKET="$(printf '%s' "$BUCKETS" | awk '{print $1}')"
for b in $BUCKETS; do
  if garage_exec bucket list 2>/dev/null | grep -qw "$b"; then
    echo "Bucket '$b' already exists, skipping."
  else
    garage_exec bucket create "$b"
    echo "Bucket '$b' created."
  fi
done

# Key (secret shown only at creation; if exists we cannot retrieve it)
KEY_CREATED=0
SECRETS_DIR="${GARAGE_SECRETS_DIR:-/secrets}"
S3_CREDS_FILE="$SECRETS_DIR/garage_s3_creds"

if garage_exec key list 2>/dev/null | grep -qw "$KEY_NAME"; then
  echo "Key '$KEY_NAME' already exists, skipping creation."
else
  echo "Creating key '$KEY_NAME'..."
  KEY_OUT="$(garage_exec key create "$KEY_NAME" 2>/dev/null)"
  echo "$KEY_OUT"
  KEY_ID="$(echo "$KEY_OUT" | awk -F': ' '/Key ID:/ { print $2; exit }' | tr -d ' ')"
  SECRET_KEY="$(echo "$KEY_OUT" | awk -F': ' '/Secret key:/ { print $2; exit }' | tr -d ' ')"

  if [ -n "$KEY_ID" ] && [ -n "$SECRET_KEY" ] && [ -d "$SECRETS_DIR" ]; then
    B1=$(echo "$BUCKETS" | awk '{print $1}')
    B2=$(echo "$BUCKETS" | awk '{print $2}')
    B3=$(echo "$BUCKETS" | awk '{print $3}')
    B4=$(echo "$BUCKETS" | awk '{print $4}')
    {
      echo "# Garage S3 credentials - generated by garage_bootstrap.sh"
      echo "# Source this file or use with your S3 client."
      echo "AWS_ACCESS_KEY_ID=$KEY_ID"
      echo "AWS_SECRET_ACCESS_KEY=$SECRET_KEY"
      echo "AWS_ENDPOINT_URL=http://127.0.0.1:3900"
      echo "AWS_DEFAULT_REGION=garage"
      echo "S3_BUCKET=$PRIMARY_BUCKET"
      echo "S3_RAW_BUCKET=${B1:-pdfs}"
      echo "S3_DOCLING_BUCKET=${B2:-$B1}"
      echo "S3_RENDERED_BUCKET=${B3:-$B1}"
      echo "S3_CHUNKS_BUCKET=${B4:-$B1}"
    } > "$S3_CREDS_FILE"
    chmod 600 "$S3_CREDS_FILE" 2>/dev/null || true
    echo "Credentials written to $S3_CREDS_FILE"
    echo "  (If owned by root: chown to your user, e.g. infra/docker/garage/secrets/garage_s3_creds)"
  else
    echo "WARNING: Could not write credentials to $S3_CREDS_FILE (save the secret above)"
  fi
  KEY_CREATED=1
fi

# Allow key on buckets
for b in $BUCKETS; do
  garage_exec bucket allow --read --write --owner "$b" --key "$KEY_NAME"
  echo "Key '$KEY_NAME' has RWO on bucket '$b'."
done

# Update bucket vars in creds file when key existed (preserves key/secret, fixes stale bucket list)
if [ "$KEY_CREATED" -eq 0 ] && [ -f "$S3_CREDS_FILE" ] && [ -w "$S3_CREDS_FILE" ]; then
  B1=$(echo "$BUCKETS" | awk '{print $1}')
  B2=$(echo "$BUCKETS" | awk '{print $2}')
  B3=$(echo "$BUCKETS" | awk '{print $3}')
  B4=$(echo "$BUCKETS" | awk '{print $4}')
  tmp=$(mktemp)
  grep -v -E '^S3_(BUCKET|RAW_BUCKET|DOCLING_BUCKET|RENDERED_BUCKET|CHUNKS_BUCKET)=' "$S3_CREDS_FILE" > "$tmp"
  {
    echo "S3_BUCKET=${B1:-pdfs}"
    echo "S3_RAW_BUCKET=${B1:-pdfs}"
    echo "S3_DOCLING_BUCKET=${B2:-$B1}"
    echo "S3_RENDERED_BUCKET=${B3:-$B1}"
    echo "S3_CHUNKS_BUCKET=${B4:-$B1}"
  } >> "$tmp"
  cat "$tmp" > "$S3_CREDS_FILE"
  rm -f "$tmp"
  echo "Updated bucket vars in $S3_CREDS_FILE"
fi

if [ "$KEY_CREATED" -eq 0 ]; then
  if [ -f "$S3_CREDS_FILE" ]; then
    echo "Existing credentials in $S3_CREDS_FILE"
  else
    echo "Key already existed. Run 'docker exec $GARAGE_CONTAINER /garage key info $KEY_NAME' for Key ID (secret is redacted)."
  fi
fi
