#!/bin/sh
# Bootstrap Langfuse: generate secrets and sync S3 credentials from Garage.
# Runs automatically on every `docker compose up` (idempotent — skips if already generated).
#
# Output: /secrets/langfuse_secrets
#   Copy the values into .env before starting langfuse-web / langfuse-worker.
#
# Reads: /garage_secrets/garage_s3_creds (written by garage_bootstrap.sh)
#   If not present yet, run garage-bootstrap first, then restart this service.

set -e

SECRETS_FILE=/secrets/langfuse_secrets
GARAGE_CREDS=/garage_secrets/garage_s3_creds
CLICKHOUSE_USER="${CLICKHOUSE_USER:-clickhouse}"

# All randomness uses /dev/urandom via busybox builtins — no apk installs needed,
# so the container can run as the host user (no root required).
rand_base64() { head -c "${1:-32}" /dev/urandom | base64 | tr -d '\n'; }
rand_hex()    { head -c "${1:-32}" /dev/urandom | od -A n -t x1 | tr -d ' \n'; }
rand_uuid()   { cat /proc/sys/kernel/random/uuid; }

# --- Crypto secrets (generated once, never overwritten) ---
if [ ! -f "$SECRETS_FILE" ]; then
  CH_PASS="$(rand_base64 32 | tr -d '/+=')"
  PK="pk-lf-$(rand_uuid)"
  SK="sk-lf-$(rand_uuid)"
  {
    printf '# Langfuse secrets — generated by langfuse_bootstrap.sh\n'
    printf '# Copy ALL of these into .env, then fill in the two USER_* lines.\n'
    printf '\n'
    printf '# --- ClickHouse ---\n'
    printf 'CLICKHOUSE_PASSWORD=%s\n'                "$CH_PASS"
    printf 'CLICKHOUSE_USER=%s\n'                    "$CLICKHOUSE_USER"
    printf '\n'
    printf '# --- Langfuse crypto ---\n'
    printf 'LANGFUSE_NEXTAUTH_SECRET=%s\n'           "$(rand_base64 32)"
    printf 'LANGFUSE_SALT=%s\n'                      "$(rand_base64 24)"
    printf 'LANGFUSE_ENCRYPTION_KEY=%s\n'            "$(rand_hex 32)"
    printf '\n'
    printf '# --- First-boot seed (org / project / user) ---\n'
    printf 'LANGFUSE_INIT_ORG_ID=%s\n'              "$(rand_uuid)"
    printf 'LANGFUSE_INIT_ORG_NAME=AI Financial Copilot\n'
    printf 'LANGFUSE_INIT_PROJECT_ID=%s\n'          "$(rand_uuid)"
    printf 'LANGFUSE_INIT_PROJECT_NAME=copilot\n'
    printf 'LANGFUSE_INIT_PROJECT_PUBLIC_KEY=%s\n'  "$PK"
    printf 'LANGFUSE_INIT_PROJECT_SECRET_KEY=%s\n'  "$SK"
    printf 'LANGFUSE_INIT_USER_PASSWORD=%s\n'       "$(rand_base64 16 | tr -d '/+=')"
    printf '# Fill these in manually:\n'
    printf 'LANGFUSE_INIT_USER_EMAIL=\n'
    printf 'LANGFUSE_INIT_USER_NAME=\n'
    printf '\n'
    printf '# --- SDK keys (same as INIT above, used by the Python SDK) ---\n'
    printf 'LANGFUSE_HOST=http://localhost:3003\n'
    printf 'LANGFUSE_PUBLIC_KEY=%s\n'               "$PK"
    printf 'LANGFUSE_SECRET_KEY=%s\n'               "$SK"
    printf 'LANGFUSE_ENABLED=true\n'
  } > "$SECRETS_FILE"
  chmod 600 "$SECRETS_FILE"
  echo "[langfuse-bootstrap] generated crypto secrets → $SECRETS_FILE"
else
  echo "[langfuse-bootstrap] crypto secrets already exist, skipping"
fi

# --- S3 credentials (synced from Garage on every run so they stay current) ---
if [ -f "$GARAGE_CREDS" ]; then
  ACCESS_KEY="$(grep '^AWS_ACCESS_KEY_ID=' "$GARAGE_CREDS" | cut -d= -f2- | tr -d '[:space:]')"
  SECRET_KEY="$(grep '^AWS_SECRET_ACCESS_KEY=' "$GARAGE_CREDS" | cut -d= -f2- | tr -d '[:space:]')"
  if [ -n "$ACCESS_KEY" ] && [ -n "$SECRET_KEY" ]; then
    tmp="$(mktemp)"
    grep -v -E '^LANGFUSE_S3_(ACCESS_KEY_ID|SECRET_ACCESS_KEY)=' "$SECRETS_FILE" > "$tmp" || true
    printf 'LANGFUSE_S3_ACCESS_KEY_ID=%s\n'     "$ACCESS_KEY" >> "$tmp"
    printf 'LANGFUSE_S3_SECRET_ACCESS_KEY=%s\n' "$SECRET_KEY" >> "$tmp"
    cat "$tmp" > "$SECRETS_FILE"
    rm -f "$tmp"
    echo "[langfuse-bootstrap] synced S3 credentials from Garage"
  else
    echo "[langfuse-bootstrap] WARNING: garage_s3_creds found but keys are empty — run garage-bootstrap first"
  fi
else
  echo "[langfuse-bootstrap] NOTE: garage_s3_creds not found — run garage-bootstrap first, then:"
  echo "[langfuse-bootstrap]   docker compose restart langfuse-secrets"
fi

# Hand ownership of the secrets file (and its directory) to the host user so
# no sudo is needed to read it outside the container.
if [ -n "${SECRETS_UID:-}" ]; then
  chown "${SECRETS_UID}:${SECRETS_GID:-$SECRETS_UID}" /secrets "$SECRETS_FILE" 2>/dev/null || true
fi

echo "[langfuse-bootstrap] done. Credentials at: infra/docker/langfuse/secrets/langfuse_secrets"
